#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-settings
Version  : 2.0.6
Release  : 10
URL      : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.jar
Source1  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.1/maven-settings-2.0.1.jar
Source2  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.1/maven-settings-2.0.1.pom
Source3  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.10/maven-settings-2.0.10.jar
Source4  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.10/maven-settings-2.0.10.pom
Source5  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.11/maven-settings-2.0.11.jar
Source6  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.11/maven-settings-2.0.11.pom
Source7  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.jar
Source8  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.pom
Source9  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.5/maven-settings-2.0.5.pom
Source10  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.pom
Source11  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.7/maven-settings-2.0.7.jar
Source12  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.7/maven-settings-2.0.7.pom
Source13  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.8/maven-settings-2.0.8.jar
Source14  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.8/maven-settings-2.0.8.pom
Source15  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.jar
Source16  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.pom
Source17  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.1.0/maven-settings-2.1.0.jar
Source18  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.1.0/maven-settings-2.1.0.pom
Source19  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.jar
Source20  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.pom
Source21  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.jar
Source22  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.pom
Source23  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.0.3/maven-settings-3.0.3.jar
Source24  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.0.3/maven-settings-3.0.3.pom
Source25  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.0.4/maven-settings-3.0.4.jar
Source26  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.0.4/maven-settings-3.0.4.pom
Source27  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.0.5/maven-settings-3.0.5.jar
Source28  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.0.5/maven-settings-3.0.5.pom
Source29  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.0/maven-settings-3.0.jar
Source30  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.0/maven-settings-3.0.pom
Source31  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.3.9/maven-settings-3.3.9.jar
Source32  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.3.9/maven-settings-3.3.9.pom
Source33  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.6.0/maven-settings-3.6.0.jar
Source34  : https://repo1.maven.org/maven2/org/apache/maven/maven-settings/3.6.0/maven-settings-3.6.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-settings-data = %{version}-%{release}
Requires: mvn-maven-settings-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-settings package.
Group: Data

%description data
data components for the mvn-maven-settings package.


%package license
Summary: license components for the mvn-maven-settings package.
Group: Default

%description license
license components for the mvn-maven-settings package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-maven-settings
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-maven-settings/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.6
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.1/maven-settings-2.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.1/maven-settings-2.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.10
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.10/maven-settings-2.0.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.10
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.10/maven-settings-2.0.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.11
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.11/maven-settings-2.0.11.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.11
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.11/maven-settings-2.0.11.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.4
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.4
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.5
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.5/maven-settings-2.0.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.6
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.7
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.7/maven-settings-2.0.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.7
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.7/maven-settings-2.0.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.8
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.8/maven-settings-2.0.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.8
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.8/maven-settings-2.0.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.9
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.9
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.1.0
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.1.0/maven-settings-2.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.1.0
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.1.0/maven-settings-2.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.0
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.0
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.1
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.1
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.3
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.3/maven-settings-3.0.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.3
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.3/maven-settings-3.0.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.4
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.4/maven-settings-3.0.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.4
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.4/maven-settings-3.0.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.5
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.5/maven-settings-3.0.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.5
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.5/maven-settings-3.0.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0/maven-settings-3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0/maven-settings-3.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.3.9
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.3.9/maven-settings-3.3.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.3.9
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.3.9/maven-settings-3.3.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.6.0
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.6.0/maven-settings-3.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.6.0
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.6.0/maven-settings-3.6.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.1/maven-settings-2.0.1.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.1/maven-settings-2.0.1.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.10/maven-settings-2.0.10.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.10/maven-settings-2.0.10.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.11/maven-settings-2.0.11.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.11/maven-settings-2.0.11.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.4/maven-settings-2.0.4.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.5/maven-settings-2.0.5.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.7/maven-settings-2.0.7.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.7/maven-settings-2.0.7.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.8/maven-settings-2.0.8.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.8/maven-settings-2.0.8.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.1.0/maven-settings-2.1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.1.0/maven-settings-2.1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.3/maven-settings-3.0.3.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.3/maven-settings-3.0.3.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.4/maven-settings-3.0.4.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.4/maven-settings-3.0.4.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.5/maven-settings-3.0.5.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0.5/maven-settings-3.0.5.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0/maven-settings-3.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.0/maven-settings-3.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.3.9/maven-settings-3.3.9.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.3.9/maven-settings-3.3.9.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.6.0/maven-settings-3.6.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-settings/3.6.0/maven-settings-3.6.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-maven-settings/LICENSE.txt
